### ISSUE TITLE
PUT does not work with GCS and FTPS

### ISSUE THREAD

**Issue by Nonius** [bolcom/libunftp#242] opened 2020-08-21 09:58 UTC
When PUT'ing a file to an unFTP instance running in GKE (Cloud instance) in FTPS mode it fails if the file size is larger than 4781 bytes.

For file size 4781 - 131194 bytes it gets stuck at 100%

```
---> STOR garbage.bin
<--- 150 Ready to receive data                     
--- Closing data socket
`garbage.bin' at 4782 (100%) [Waiting for transfer to complete]
```

For larger files (131195+ bytes) it fails with a 550:

```
---> STOR garbage.bin
<--- 150 Ready to receive data                     
--- Closing data socket                                              
<--- 550 File not found                                                              
put: Access failed: 550 File not found (garbage.bin)
```

**Comment by hannesdejager** [comment] 2020-08-30 20:42
Cannot reproduce.

**Comment by robklg** [comment] 2020-08-31 12:06
Reproduced this issue with v0.11.0 and v0.12.0. The error occurs when uploading a file of size 4782 bytes (4781, still works).
The symptom is upload gets stuck at 100% progress.

Tested with alpine docker images.

**Comment by robklg** [comment] 2020-10-02 19:14
Reproduced also with the filesystem backend. Same issue.

**Comment by robklg** [comment] 2020-10-16 08:45
> For file size 4781 - 131194 bytes it gets stuck at 100%

This is no longer the case. After upgrading, I get a 550 for all uploads larger than 4781

**Comment by hannesdejager** [comment] 2020-11-13 09:40
Closing in favour of #285

**Closed by hannesdejager** 2020-11-13 09:40 UTC
Labels: bug
